name: Next.js Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-nextjs-app .

      - name: Run container
        run: |
          docker run -d -p 3000:3000 --name test-app my-nextjs-app
          sleep 10  # attendre que l'app démarre

      - name: Test if Next.js app is running
        run: |
          curl --fail http://localhost:3000 || (docker logs test-app && exit 1)

      - name: Stop and remove container
        run: |
          docker stop test-app
          docker rm test-app
